In [4]:
import numpy as np

list=[0,1,2,3,4,5,6,7,8]

list

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [46]:
matrix = np.array(list).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [87]:
sumA1 = matrix.sum(axis=0)
meanA2 = matrix.mean(axis=1)
sumFlat = matrix.sum()

In [72]:
matrix.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [70]:
print(sumA1)

[ 9 12 15]


In [113]:
meanA2.tolist()

[1.0, 4.0, 7.0]

In [69]:
sumFlat

36

In [107]:
numero = 1.
f'{numero:.4f}'
# round(numero, 0)

'1.0000'

1.0

main output

{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0], 'variance': [[6.0, 6.0, 6.0], [6.0, 6.0, 6.0], 6.666666666666667], 'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611], 'max': [[6, 7, 8], [2, 5, 8], 8], 'min': [[0, 1, 2], [0, 3, 6], 0], 'sum': [[9, 12, 15], [3, 12, 21], 36]}

expected

{
  'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
  'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667],
  'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611],
  'max': [[6, 7, 8], [2, 5, 8], 8],
  'min': [[0, 1, 2], [0, 3, 6], 0],
  'sum': [[9, 12, 15], [3, 12, 21], 36]
}